/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as WelcomeRouteImport } from './app/welcome'
import { Route as SetupRouteImport } from './app/setup'
import { Route as SettingsRouteImport } from './app/settings'
import { Route as JoinRouteImport } from './app/join'
import { Route as HistoryRouteImport } from './app/history'
import { Route as DashboardRouteImport } from './app/dashboard'
import { Route as ClaimLinkRouteImport } from './app/claim-link'
import { Route as IndexRouteImport } from './app/index'
import { Route as StreamsIndexRouteImport } from './app/streams/index'
import { Route as RewardsIndexRouteImport } from './app/rewards/index'
import { Route as MeIndexRouteImport } from './app/me/index'
import { Route as FamilyIndexRouteImport } from './app/family/index'
import { Route as CirclesIndexRouteImport } from './app/circles/index'
import { Route as AllowanceIndexRouteImport } from './app/allowance/index'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimLinkRoute = ClaimLinkRouteImport.update({
  id: '/claim-link',
  path: '/claim-link',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamsIndexRoute = StreamsIndexRouteImport.update({
  id: '/streams/',
  path: '/streams/',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsIndexRoute = RewardsIndexRouteImport.update({
  id: '/rewards/',
  path: '/rewards/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeIndexRoute = MeIndexRouteImport.update({
  id: '/me/',
  path: '/me/',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyIndexRoute = FamilyIndexRouteImport.update({
  id: '/family/',
  path: '/family/',
  getParentRoute: () => rootRouteImport,
} as any)
const CirclesIndexRoute = CirclesIndexRouteImport.update({
  id: '/circles/',
  path: '/circles/',
  getParentRoute: () => rootRouteImport,
} as any)
const AllowanceIndexRoute = AllowanceIndexRouteImport.update({
  id: '/allowance/',
  path: '/allowance/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/claim-link': typeof ClaimLinkRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/join': typeof JoinRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/welcome': typeof WelcomeRoute
  '/allowance/': typeof AllowanceIndexRoute
  '/circles/': typeof CirclesIndexRoute
  '/family/': typeof FamilyIndexRoute
  '/me/': typeof MeIndexRoute
  '/rewards/': typeof RewardsIndexRoute
  '/streams/': typeof StreamsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/claim-link': typeof ClaimLinkRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/join': typeof JoinRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/welcome': typeof WelcomeRoute
  '/allowance': typeof AllowanceIndexRoute
  '/circles': typeof CirclesIndexRoute
  '/family': typeof FamilyIndexRoute
  '/me': typeof MeIndexRoute
  '/rewards': typeof RewardsIndexRoute
  '/streams': typeof StreamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/claim-link': typeof ClaimLinkRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/join': typeof JoinRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/welcome': typeof WelcomeRoute
  '/allowance/': typeof AllowanceIndexRoute
  '/circles/': typeof CirclesIndexRoute
  '/family/': typeof FamilyIndexRoute
  '/me/': typeof MeIndexRoute
  '/rewards/': typeof RewardsIndexRoute
  '/streams/': typeof StreamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/claim-link'
    | '/dashboard'
    | '/history'
    | '/join'
    | '/settings'
    | '/setup'
    | '/welcome'
    | '/allowance/'
    | '/circles/'
    | '/family/'
    | '/me/'
    | '/rewards/'
    | '/streams/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/claim-link'
    | '/dashboard'
    | '/history'
    | '/join'
    | '/settings'
    | '/setup'
    | '/welcome'
    | '/allowance'
    | '/circles'
    | '/family'
    | '/me'
    | '/rewards'
    | '/streams'
  id:
    | '__root__'
    | '/'
    | '/claim-link'
    | '/dashboard'
    | '/history'
    | '/join'
    | '/settings'
    | '/setup'
    | '/welcome'
    | '/allowance/'
    | '/circles/'
    | '/family/'
    | '/me/'
    | '/rewards/'
    | '/streams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClaimLinkRoute: typeof ClaimLinkRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  JoinRoute: typeof JoinRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  WelcomeRoute: typeof WelcomeRoute
  AllowanceIndexRoute: typeof AllowanceIndexRoute
  CirclesIndexRoute: typeof CirclesIndexRoute
  FamilyIndexRoute: typeof FamilyIndexRoute
  MeIndexRoute: typeof MeIndexRoute
  RewardsIndexRoute: typeof RewardsIndexRoute
  StreamsIndexRoute: typeof StreamsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim-link': {
      id: '/claim-link'
      path: '/claim-link'
      fullPath: '/claim-link'
      preLoaderRoute: typeof ClaimLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streams/': {
      id: '/streams/'
      path: '/streams'
      fullPath: '/streams/'
      preLoaderRoute: typeof StreamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards/': {
      id: '/rewards/'
      path: '/rewards'
      fullPath: '/rewards/'
      preLoaderRoute: typeof RewardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/': {
      id: '/me/'
      path: '/me'
      fullPath: '/me/'
      preLoaderRoute: typeof MeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family/': {
      id: '/family/'
      path: '/family'
      fullPath: '/family/'
      preLoaderRoute: typeof FamilyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circles/': {
      id: '/circles/'
      path: '/circles'
      fullPath: '/circles/'
      preLoaderRoute: typeof CirclesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allowance/': {
      id: '/allowance/'
      path: '/allowance'
      fullPath: '/allowance/'
      preLoaderRoute: typeof AllowanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClaimLinkRoute: ClaimLinkRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  JoinRoute: JoinRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  WelcomeRoute: WelcomeRoute,
  AllowanceIndexRoute: AllowanceIndexRoute,
  CirclesIndexRoute: CirclesIndexRoute,
  FamilyIndexRoute: FamilyIndexRoute,
  MeIndexRoute: MeIndexRoute,
  RewardsIndexRoute: RewardsIndexRoute,
  StreamsIndexRoute: StreamsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
