/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AllowanceRouteImport } from './routes/allowance'
import { Route as ChoresRouteImport } from './routes/chores'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as JoinRouteImport } from './routes/join'
import { Route as MeRouteImport } from './routes/me'
import { Route as PotRouteImport } from './routes/pot'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as StashRouteImport } from './routes/stash'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as DevBoardRouteImport } from './routes/dev.board'
import { Route as DevMoneyRouteImport } from './routes/dev.money'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AllowanceRoute = AllowanceRouteImport.update({
  id: '/allowance',
  path: '/allowance',
  getParentRoute: () => rootRouteImport,
} as any)
const ChoresRoute = ChoresRouteImport.update({
  id: '/chores',
  path: '/chores',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const PotRoute = PotRouteImport.update({
  id: '/pot',
  path: '/pot',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const StashRoute = StashRouteImport.update({
  id: '/stash',
  path: '/stash',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const DevBoardRoute = DevBoardRouteImport.update({
  id: '/dev/board',
  path: '/dev/board',
  getParentRoute: () => rootRouteImport,
} as any)
const DevMoneyRoute = DevMoneyRouteImport.update({
  id: '/dev/money',
  path: '/dev/money',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/allowance': typeof AllowanceRoute
  '/chores': typeof ChoresRoute
  '/dashboard': typeof DashboardRoute
  '/family': typeof FamilyRoute
  '/goals': typeof GoalsRoute
  '/join': typeof JoinRoute
  '/me': typeof MeRoute
  '/pot': typeof PotRoute
  '/setup': typeof SetupRoute
  '/stash': typeof StashRoute
  '/welcome': typeof WelcomeRoute
  '/dev/board': typeof DevBoardRoute
  '/dev/money': typeof DevMoneyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/allowance': typeof AllowanceRoute
  '/chores': typeof ChoresRoute
  '/dashboard': typeof DashboardRoute
  '/family': typeof FamilyRoute
  '/goals': typeof GoalsRoute
  '/join': typeof JoinRoute
  '/me': typeof MeRoute
  '/pot': typeof PotRoute
  '/setup': typeof SetupRoute
  '/stash': typeof StashRoute
  '/welcome': typeof WelcomeRoute
  '/dev/board': typeof DevBoardRoute
  '/dev/money': typeof DevMoneyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/allowance': typeof AllowanceRoute
  '/chores': typeof ChoresRoute
  '/dashboard': typeof DashboardRoute
  '/family': typeof FamilyRoute
  '/goals': typeof GoalsRoute
  '/join': typeof JoinRoute
  '/me': typeof MeRoute
  '/pot': typeof PotRoute
  '/setup': typeof SetupRoute
  '/stash': typeof StashRoute
  '/welcome': typeof WelcomeRoute
  '/dev/board': typeof DevBoardRoute
  '/dev/money': typeof DevMoneyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/allowance'
    | '/chores'
    | '/dashboard'
    | '/family'
    | '/goals'
    | '/join'
    | '/me'
    | '/pot'
    | '/setup'
    | '/stash'
    | '/welcome'
    | '/dev/board'
    | '/dev/money'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/allowance'
    | '/chores'
    | '/dashboard'
    | '/family'
    | '/goals'
    | '/join'
    | '/me'
    | '/pot'
    | '/setup'
    | '/stash'
    | '/welcome'
    | '/dev/board'
    | '/dev/money'
  id:
    | '__root__'
    | '/'
    | '/allowance'
    | '/chores'
    | '/dashboard'
    | '/family'
    | '/goals'
    | '/join'
    | '/me'
    | '/pot'
    | '/setup'
    | '/stash'
    | '/welcome'
    | '/dev/board'
    | '/dev/money'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllowanceRoute: typeof AllowanceRoute
  ChoresRoute: typeof ChoresRoute
  DashboardRoute: typeof DashboardRoute
  FamilyRoute: typeof FamilyRoute
  GoalsRoute: typeof GoalsRoute
  JoinRoute: typeof JoinRoute
  MeRoute: typeof MeRoute
  PotRoute: typeof PotRoute
  SetupRoute: typeof SetupRoute
  StashRoute: typeof StashRoute
  WelcomeRoute: typeof WelcomeRoute
  DevBoardRoute: typeof DevBoardRoute
  DevMoneyRoute: typeof DevMoneyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allowance': {
      id: '/allowance'
      path: '/allowance'
      fullPath: '/allowance'
      preLoaderRoute: typeof AllowanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chores': {
      id: '/chores'
      path: '/chores'
      fullPath: '/chores'
      preLoaderRoute: typeof ChoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pot': {
      id: '/pot'
      path: '/pot'
      fullPath: '/pot'
      preLoaderRoute: typeof PotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stash': {
      id: '/stash'
      path: '/stash'
      fullPath: '/stash'
      preLoaderRoute: typeof StashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/board': {
      id: '/dev/board'
      path: '/dev/board'
      fullPath: '/dev/board'
      preLoaderRoute: typeof DevBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/money': {
      id: '/dev/money'
      path: '/dev/money'
      fullPath: '/dev/money'
      preLoaderRoute: typeof DevMoneyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllowanceRoute: AllowanceRoute,
  ChoresRoute: ChoresRoute,
  DashboardRoute: DashboardRoute,
  FamilyRoute: FamilyRoute,
  GoalsRoute: GoalsRoute,
  JoinRoute: JoinRoute,
  MeRoute: MeRoute,
  PotRoute: PotRoute,
  SetupRoute: SetupRoute,
  StashRoute: StashRoute,
  WelcomeRoute: WelcomeRoute,
  DevBoardRoute: DevBoardRoute,
  DevMoneyRoute: DevMoneyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
