//! End-to-end validation that a *real* remint proof — generated by snarkjs from
//! the existing `remint_final.zkey` — verifies on Soroban and drives the pool.

use soroban_sdk::{
    crypto::bn254::Bn254Fr,
    testutils::Address as _,
    token::{StellarAssetClient, TokenClient},
    Address, Bytes, BytesN, Env, U256, Vec,
};

use contract_types::Groth16Proof;

use crate::remint_fixture as fx;
use crate::{Zwerc20, Zwerc20Client};

fn u256(env: &Env, b: &[u8; 32]) -> U256 {
    U256::from_be_bytes(env, &Bytes::from_array(env, b))
}

/// The core claim: the Soroban BN254 verifier accepts a real circuit proof.
#[test]
fn real_proof_verifies_on_soroban() {
    let env = Env::default();
    let vid = env.register(groth16_verifier::CircomGroth16Verifier, ());
    let verifier = groth16_verifier::CircomGroth16VerifierClient::new(&env, &vid);

    let proof = Groth16Proof::try_from(Bytes::from_array(&env, &fx::PROOF)).unwrap();
    let mut inputs: Vec<Bn254Fr> = Vec::new(&env);
    for sig in fx::PUBLIC_SIGNALS.iter() {
        inputs.push_back(Bn254Fr::from_bytes(BytesN::from_array(&env, sig)));
    }

    assert!(verifier.verify(&proof, &inputs), "real remint proof must verify");
}

/// Full flow: deposit a note, then withdraw it privately with the real proof;
/// the recipient is paid, the nullifier is spent, and a replay is rejected.
#[test]
fn remint_e2e_pays_recipient_and_blocks_replay() {
    let env = Env::default();
    env.mock_all_auths();

    let vid = env.register(groth16_verifier::CircomGroth16Verifier, ());

    // Underlying asset (a test SAC).
    let sac_admin = Address::generate(&env);
    let sac = env.register_stellar_asset_contract_v2(sac_admin);
    let token = sac.address();
    let token_admin = StellarAssetClient::new(&env, &token);

    // The pool.
    let admin = Address::generate(&env);
    let zid = env.register(Zwerc20, ());
    let z = Zwerc20Client::new(&env, &zid);
    z.init(&admin, &token, &vid);

    // A depositor funds the pool and inserts the note's commitment.
    let depositor = Address::generate(&env);
    token_admin.mint(&depositor, &1_000_000);
    let commitment = u256(&env, &fx::COMMITMENT);
    z.deposit(&depositor, &commitment, &1_000_000);

    // The on-chain root now equals the root the proof was generated against.
    assert_eq!(z.current_root(), u256(&env, &fx::ROOT));

    // The recipient withdraws privately via the real proof.
    let to = Address::generate(&env);
    let root = u256(&env, &fx::PUBLIC_SIGNALS[0]);
    let nullifier = u256(&env, &fx::PUBLIC_SIGNALS[1]);
    let to_field = u256(&env, &fx::PUBLIC_SIGNALS[2]);
    let relayer_fee = u256(&env, &fx::PUBLIC_SIGNALS[6]);
    let proof = Bytes::from_array(&env, &fx::PROOF);

    z.remint(&to, &to_field, &1_000_000, &root, &nullifier, &relayer_fee, &proof);

    assert_eq!(TokenClient::new(&env, &token).balance(&to), 1_000_000);
    assert!(z.is_nullifier_used(&nullifier));

    // Replay with the same nullifier must be rejected.
    let replay = z.try_remint(&to, &to_field, &1_000_000, &root, &nullifier, &relayer_fee, &proof);
    assert!(replay.is_err(), "nullifier replay must be rejected");
}
