//! Build script for `groth16-verifier`.
//!
//! Reads a snarkjs `verification_key.json` from the path given by the
//! `VERIFIER_VK_JSON` environment variable and generates `vk.rs` in the Cargo
//! output directory. `lib.rs` includes that file at compile time, embedding the
//! verification key as static byte arrays (no persistent storage).
//!
//! ```bash
//! VERIFIER_VK_JSON=/abs/path/verification_key.json \
//!   cargo build -p groth16-verifier --release
//! ```
//!
//! Self-contained: the snarkjs-decimal -> Soroban-bytes conversion is inlined
//! here (G1 = x||y big-endian, 64 bytes; G2 = x.c1||x.c0||y.c1||y.c0, Soroban's
//! imaginary||real ordering, 128 bytes).

use std::{env, fmt::Write as _, fs, path::PathBuf};

use ark_bn254::{Fq, Fq2, g1::G1Affine, g2::G2Affine};
use ark_ff::{BigInteger, PrimeField};
use num_bigint::BigUint;
use serde_json::Value;

fn parse_fq_decimal(value: &str) -> Fq {
    let bi = BigUint::parse_bytes(value.as_bytes(), 10)
        .unwrap_or_else(|| panic!("invalid decimal field element: {value}"));
    Fq::from_be_bytes_mod_order(&bi.to_bytes_be())
}

fn bigint_to_be_32<B: BigInteger>(value: B) -> [u8; 32] {
    let bytes = value.to_bytes_be();
    let mut out = [0u8; 32];
    let n = bytes.len().min(32);
    out[32 - n..].copy_from_slice(&bytes[bytes.len() - n..]);
    out
}

fn g1_to_soroban_bytes(p: &G1Affine) -> [u8; 64] {
    let mut out = [0u8; 64];
    out[..32].copy_from_slice(&bigint_to_be_32(p.x.into_bigint()));
    out[32..].copy_from_slice(&bigint_to_be_32(p.y.into_bigint()));
    out
}

/// Soroban G2 byte order: imaginary (c1) before real (c0).
fn g2_to_soroban_bytes(p: &G2Affine) -> [u8; 128] {
    let mut out = [0u8; 128];
    out[..32].copy_from_slice(&bigint_to_be_32(p.x.c1.into_bigint()));
    out[32..64].copy_from_slice(&bigint_to_be_32(p.x.c0.into_bigint()));
    out[64..96].copy_from_slice(&bigint_to_be_32(p.y.c1.into_bigint()));
    out[96..].copy_from_slice(&bigint_to_be_32(p.y.c0.into_bigint()));
    out
}

/// snarkjs G1 `[x, y, "1"]` -> 64 bytes.
fn g1_bytes(pt: &Value) -> [u8; 64] {
    let a = pt.as_array().expect("G1 point must be an array");
    let x = parse_fq_decimal(a[0].as_str().expect("G1.x string"));
    let y = parse_fq_decimal(a[1].as_str().expect("G1.y string"));
    g1_to_soroban_bytes(&G1Affine::new_unchecked(x, y))
}

/// snarkjs G2 `[[x.c0, x.c1], [y.c0, y.c1], ["1","0"]]` -> 128 bytes.
fn g2_bytes(pt: &Value) -> [u8; 128] {
    let a = pt.as_array().expect("G2 point must be an array");
    let x = a[0].as_array().expect("G2.x must be an array");
    let y = a[1].as_array().expect("G2.y must be an array");
    let xf = Fq2::new(
        parse_fq_decimal(x[0].as_str().expect("G2.x.c0 string")),
        parse_fq_decimal(x[1].as_str().expect("G2.x.c1 string")),
    );
    let yf = Fq2::new(
        parse_fq_decimal(y[0].as_str().expect("G2.y.c0 string")),
        parse_fq_decimal(y[1].as_str().expect("G2.y.c1 string")),
    );
    g2_to_soroban_bytes(&G2Affine::new_unchecked(xf, yf))
}

fn fmt_bytes(bytes: &[u8]) -> String {
    let mut s = String::from("[");
    for (i, b) in bytes.iter().enumerate() {
        if i > 0 {
            s.push(',');
        }
        write!(s, "0x{b:02x}").expect("write to String");
    }
    s.push(']');
    s
}

fn vk_rs_from_json(json: &str) -> String {
    let v: Value = serde_json::from_str(json).expect("VK file is not valid JSON");

    let alpha = g1_bytes(&v["vk_alpha_1"]);
    let beta = g2_bytes(&v["vk_beta_2"]);
    let gamma = g2_bytes(&v["vk_gamma_2"]);
    let delta = g2_bytes(&v["vk_delta_2"]);

    let ic_arr = v["IC"].as_array().expect("IC must be an array");
    let ic_len = ic_arr.len();
    let ic_items: Vec<String> = ic_arr.iter().map(|pt| fmt_bytes(&g1_bytes(pt))).collect();

    let mut out = String::new();
    writeln!(out, "// Auto-generated by build.rs — do not edit.").unwrap();
    writeln!(out, "const VK_ALPHA_G1: [u8; 64] = {};", fmt_bytes(&alpha)).unwrap();
    writeln!(out, "const VK_BETA_G2: [u8; 128] = {};", fmt_bytes(&beta)).unwrap();
    writeln!(out, "const VK_GAMMA_G2: [u8; 128] = {};", fmt_bytes(&gamma)).unwrap();
    writeln!(out, "const VK_DELTA_G2: [u8; 128] = {};", fmt_bytes(&delta)).unwrap();
    writeln!(
        out,
        "const VK_IC: [[u8; 64]; {ic_len}] = [{}];",
        ic_items.join(",")
    )
    .unwrap();
    out
}

fn main() {
    println!("cargo:rerun-if-env-changed=VERIFIER_VK_JSON");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR not set"));
    let path = PathBuf::from(env::var("VERIFIER_VK_JSON").expect("VERIFIER_VK_JSON not set"));
    println!("cargo:rerun-if-changed={}", path.display());
    let json = fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("failed to read VK file `{}`: {e}", path.display()));
    fs::write(out_dir.join("vk.rs"), vk_rs_from_json(&json)).expect("failed to write vk.rs");
}
