//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// AddressDriver
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const addressDriverAbi = [
  {
    type: 'constructor',
    inputs: [
      { name: 'drips_', internalType: 'contract IDrips', type: 'address' },
      { name: 'forwarder', internalType: 'address', type: 'address' },
      { name: 'driverId_', internalType: 'uint32', type: 'uint32' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'DRIPS',
    outputs: [{ name: '', internalType: 'contract IDrips', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'DRIVER_ID',
    outputs: [{ name: '', internalType: 'uint32', type: 'uint32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'acceptAdmin',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'admin',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'allPausers',
    outputs: [{ name: 'pausersList', internalType: 'address[]', type: 'address[]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'addr', internalType: 'address', type: 'address' }],
    name: 'calcAccountId',
    outputs: [{ name: 'accountId', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'erc20', internalType: 'contract IERC20', type: 'address' },
      { name: 'transferTo', internalType: 'address', type: 'address' },
    ],
    name: 'collect',
    outputs: [{ name: 'amt', internalType: 'uint128', type: 'uint128' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      {
        name: 'accountMetadata',
        internalType: 'struct AccountMetadata[]',
        type: 'tuple[]',
        components: [
          { name: 'key', internalType: 'bytes32', type: 'bytes32' },
          { name: 'value', internalType: 'bytes', type: 'bytes' },
        ],
      },
    ],
    name: 'emitAccountMetadata',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'erc20', internalType: 'contract IERC20', type: 'address' },
      { name: 'yieldManager', internalType: 'address', type: 'address' },
      { name: 'strategy', internalType: 'address', type: 'address' },
      { name: 'senderAccountId', internalType: 'uint256', type: 'uint256' },
      { name: 'transferTo', internalType: 'address', type: 'address' },
      { name: 'strategyData', internalType: 'bytes', type: 'bytes' },
    ],
    name: 'forceCollect',
    outputs: [{ name: 'amt', internalType: 'uint128', type: 'uint128' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'receiver', internalType: 'uint256', type: 'uint256' },
      { name: 'erc20', internalType: 'contract IERC20', type: 'address' },
      { name: 'amt', internalType: 'uint128', type: 'uint128' },
    ],
    name: 'give',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'pauser', internalType: 'address', type: 'address' }],
    name: 'grantPauser',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'implementation',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'isPaused',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'pauser', internalType: 'address', type: 'address' }],
    name: 'isPauser',
    outputs: [{ name: 'isAddrPauser', internalType: 'bool', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'forwarder', internalType: 'address', type: 'address' }],
    name: 'isTrustedForwarder',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'pause',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'newAdmin', internalType: 'address', type: 'address' }],
    name: 'proposeNewAdmin',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'proposedAdmin',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'proxiableUUID',
    outputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'renounceAdmin',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'pauser', internalType: 'address', type: 'address' }],
    name: 'revokePauser',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      {
        name: 'receivers',
        internalType: 'struct SplitsReceiver[]',
        type: 'tuple[]',
        components: [
          { name: 'accountId', internalType: 'uint256', type: 'uint256' },
          { name: 'weight', internalType: 'uint32', type: 'uint32' },
        ],
      },
    ],
    name: 'setSplits',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'erc20', internalType: 'contract IERC20', type: 'address' },
      {
        name: 'currReceivers',
        internalType: 'struct StreamReceiver[]',
        type: 'tuple[]',
        components: [
          { name: 'accountId', internalType: 'uint256', type: 'uint256' },
          { name: 'config', internalType: 'StreamConfig', type: 'uint256' },
        ],
      },
      { name: 'balanceDelta', internalType: 'int128', type: 'int128' },
      {
        name: 'newReceivers',
        internalType: 'struct StreamReceiver[]',
        type: 'tuple[]',
        components: [
          { name: 'accountId', internalType: 'uint256', type: 'uint256' },
          { name: 'config', internalType: 'StreamConfig', type: 'uint256' },
        ],
      },
      { name: 'maxEndHint1', internalType: 'uint32', type: 'uint32' },
      { name: 'maxEndHint2', internalType: 'uint32', type: 'uint32' },
      { name: 'transferTo', internalType: 'address', type: 'address' },
    ],
    name: 'setStreams',
    outputs: [{ name: 'realBalanceDelta', internalType: 'int128', type: 'int128' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'unpause',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'newImplementation', internalType: 'address', type: 'address' }],
    name: 'upgradeTo',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'newImplementation', internalType: 'address', type: 'address' },
      { name: 'data', internalType: 'bytes', type: 'bytes' },
    ],
    name: 'upgradeToAndCall',
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'previousAdmin', internalType: 'address', type: 'address', indexed: false },
      { name: 'newAdmin', internalType: 'address', type: 'address', indexed: false },
    ],
    name: 'AdminChanged',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'beacon', internalType: 'address', type: 'address', indexed: true }],
    name: 'BeaconUpgraded',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'currentAdmin', internalType: 'address', type: 'address', indexed: true },
      { name: 'newAdmin', internalType: 'address', type: 'address', indexed: true },
    ],
    name: 'NewAdminProposed',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'pauser', internalType: 'address', type: 'address', indexed: true }],
    name: 'Paused',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'pauser', internalType: 'address', type: 'address', indexed: true },
      { name: 'admin', internalType: 'address', type: 'address', indexed: true },
    ],
    name: 'PauserGranted',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'pauser', internalType: 'address', type: 'address', indexed: true },
      { name: 'admin', internalType: 'address', type: 'address', indexed: true },
    ],
    name: 'PauserRevoked',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'pauser', internalType: 'address', type: 'address', indexed: true }],
    name: 'Unpaused',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'implementation', internalType: 'address', type: 'address', indexed: true },
    ],
    name: 'Upgraded',
  },
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// DripsFacetA
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const dripsFacetAAbi = [
  {
    type: 'constructor',
    inputs: [{ name: 'cycleSecs_', internalType: 'uint32', type: 'uint32' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'AMT_PER_SEC_EXTRA_DECIMALS',
    outputs: [{ name: '', internalType: 'uint8', type: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'AMT_PER_SEC_MULTIPLIER',
    outputs: [{ name: '', internalType: 'uint160', type: 'uint160' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'CYCLE_SECS',
    outputs: [{ name: '', internalType: 'uint32', type: 'uint32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'DRIVER_ID_OFFSET',
    outputs: [{ name: '', internalType: 'uint8', type: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'MAX_STREAMS_RECEIVERS',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'MAX_TOTAL_BALANCE',
    outputs: [{ name: '', internalType: 'uint128', type: 'uint128' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'MIN_AMT_PER_SEC',
    outputs: [{ name: '', internalType: 'uint160', type: 'uint160' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'acceptAdmin',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'admin',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'allPausers',
    outputs: [{ name: 'pausersList', internalType: 'address[]', type: 'address[]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'erc20', internalType: 'contract IERC20', type: 'address' }],
    name: 'balances',
    outputs: [
      { name: 'streamsBalance', internalType: 'uint128', type: 'uint128' },
      { name: 'splitsBalance', internalType: 'uint128', type: 'uint128' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'driverId', internalType: 'uint32', type: 'uint32' }],
    name: 'driverAddress',
    outputs: [{ name: 'driverAddr', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'pauser', internalType: 'address', type: 'address' }],
    name: 'grantPauser',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'implementation',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'isPaused',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'pauser', internalType: 'address', type: 'address' }],
    name: 'isPauser',
    outputs: [{ name: 'isAddrPauser', internalType: 'bool', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'nextDriverId',
    outputs: [{ name: 'driverId', internalType: 'uint32', type: 'uint32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'pause',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'newAdmin', internalType: 'address', type: 'address' }],
    name: 'proposeNewAdmin',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'proposedAdmin',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'proxiableUUID',
    outputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'accountId', internalType: 'uint256', type: 'uint256' },
      { name: 'erc20', internalType: 'contract IERC20', type: 'address' },
      { name: 'maxCycles', internalType: 'uint32', type: 'uint32' },
    ],
    name: 'receiveStreams',
    outputs: [{ name: 'receivedAmt', internalType: 'uint128', type: 'uint128' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'driverAddr', internalType: 'address', type: 'address' }],
    name: 'registerDriver',
    outputs: [{ name: 'driverId', internalType: 'uint32', type: 'uint32' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'renounceAdmin',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'pauser', internalType: 'address', type: 'address' }],
    name: 'revokePauser',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'accountId', internalType: 'uint256', type: 'uint256' },
      { name: 'erc20', internalType: 'contract IERC20', type: 'address' },
      {
        name: 'currReceivers',
        internalType: 'struct StreamReceiver[]',
        type: 'tuple[]',
        components: [
          { name: 'accountId', internalType: 'uint256', type: 'uint256' },
          { name: 'config', internalType: 'StreamConfig', type: 'uint256' },
        ],
      },
      { name: 'balanceDelta', internalType: 'int128', type: 'int128' },
      {
        name: 'newReceivers',
        internalType: 'struct StreamReceiver[]',
        type: 'tuple[]',
        components: [
          { name: 'accountId', internalType: 'uint256', type: 'uint256' },
          { name: 'config', internalType: 'StreamConfig', type: 'uint256' },
        ],
      },
      { name: 'maxEndHint1', internalType: 'uint32', type: 'uint32' },
      { name: 'maxEndHint2', internalType: 'uint32', type: 'uint32' },
    ],
    name: 'setStreams',
    outputs: [{ name: 'realBalanceDelta', internalType: 'int128', type: 'int128' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'accountId', internalType: 'uint256', type: 'uint256' },
      { name: 'erc20', internalType: 'contract IERC20', type: 'address' },
    ],
    name: 'streamsState',
    outputs: [
      { name: 'streamsHash', internalType: 'bytes32', type: 'bytes32' },
      { name: 'streamsHistoryHash', internalType: 'bytes32', type: 'bytes32' },
      { name: 'updateTime', internalType: 'uint32', type: 'uint32' },
      { name: 'balance', internalType: 'uint128', type: 'uint128' },
      { name: 'maxEnd', internalType: 'uint32', type: 'uint32' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'unpause',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'driverId', internalType: 'uint32', type: 'uint32' },
      { name: 'newDriverAddr', internalType: 'address', type: 'address' },
    ],
    name: 'updateDriverAddress',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'newImplementation', internalType: 'address', type: 'address' }],
    name: 'upgradeTo',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'newImplementation', internalType: 'address', type: 'address' },
      { name: 'data', internalType: 'bytes', type: 'bytes' },
    ],
    name: 'upgradeToAndCall',
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'erc20', internalType: 'contract IERC20', type: 'address' },
      { name: 'receiver', internalType: 'address', type: 'address' },
      { name: 'amt', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'withdraw',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'previousAdmin', internalType: 'address', type: 'address', indexed: false },
      { name: 'newAdmin', internalType: 'address', type: 'address', indexed: false },
    ],
    name: 'AdminChanged',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'beacon', internalType: 'address', type: 'address', indexed: true }],
    name: 'BeaconUpgraded',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'accountId', internalType: 'uint256', type: 'uint256', indexed: true },
      { name: 'erc20', internalType: 'contract IERC20', type: 'address', indexed: true },
      { name: 'amt', internalType: 'uint128', type: 'uint128', indexed: false },
    ],
    name: 'Collectable',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'accountId', internalType: 'uint256', type: 'uint256', indexed: true },
      { name: 'erc20', internalType: 'contract IERC20', type: 'address', indexed: true },
      { name: 'collected', internalType: 'uint128', type: 'uint128', indexed: false },
    ],
    name: 'Collected',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'driverId', internalType: 'uint32', type: 'uint32', indexed: true },
      { name: 'oldDriverAddr', internalType: 'address', type: 'address', indexed: true },
      { name: 'newDriverAddr', internalType: 'address', type: 'address', indexed: true },
    ],
    name: 'DriverAddressUpdated',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'driverId', internalType: 'uint32', type: 'uint32', indexed: true },
      { name: 'driverAddr', internalType: 'address', type: 'address', indexed: true },
    ],
    name: 'DriverRegistered',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'accountId', internalType: 'uint256', type: 'uint256', indexed: true },
      { name: 'receiver', internalType: 'uint256', type: 'uint256', indexed: true },
      { name: 'erc20', internalType: 'contract IERC20', type: 'address', indexed: true },
      { name: 'amt', internalType: 'uint128', type: 'uint128', indexed: false },
    ],
    name: 'Given',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'currentAdmin', internalType: 'address', type: 'address', indexed: true },
      { name: 'newAdmin', internalType: 'address', type: 'address', indexed: true },
    ],
    name: 'NewAdminProposed',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'pauser', internalType: 'address', type: 'address', indexed: true }],
    name: 'Paused',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'pauser', internalType: 'address', type: 'address', indexed: true },
      { name: 'admin', internalType: 'address', type: 'address', indexed: true },
    ],
    name: 'PauserGranted',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'pauser', internalType: 'address', type: 'address', indexed: true },
      { name: 'admin', internalType: 'address', type: 'address', indexed: true },
    ],
    name: 'PauserRevoked',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'accountId', internalType: 'uint256', type: 'uint256', indexed: true },
      { name: 'erc20', internalType: 'contract IERC20', type: 'address', indexed: true },
      { name: 'amt', internalType: 'uint128', type: 'uint128', indexed: false },
      { name: 'receivableCycles', internalType: 'uint32', type: 'uint32', indexed: false },
    ],
    name: 'ReceivedStreams',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'accountId', internalType: 'uint256', type: 'uint256', indexed: true },
      { name: 'receiver', internalType: 'uint256', type: 'uint256', indexed: true },
      { name: 'erc20', internalType: 'contract IERC20', type: 'address', indexed: true },
      { name: 'amt', internalType: 'uint128', type: 'uint128', indexed: false },
    ],
    name: 'Split',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'receiversHash', internalType: 'bytes32', type: 'bytes32', indexed: true },
      { name: 'accountId', internalType: 'uint256', type: 'uint256', indexed: true },
      { name: 'weight', internalType: 'uint32', type: 'uint32', indexed: false },
    ],
    name: 'SplitsReceiverSeen',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'accountId', internalType: 'uint256', type: 'uint256', indexed: true },
      { name: 'receiversHash', internalType: 'bytes32', type: 'bytes32', indexed: true },
    ],
    name: 'SplitsSet',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'accountId', internalType: 'uint256', type: 'uint256', indexed: true },
      { name: 'erc20', internalType: 'contract IERC20', type: 'address', indexed: true },
      { name: 'senderId', internalType: 'uint256', type: 'uint256', indexed: true },
      { name: 'amt', internalType: 'uint128', type: 'uint128', indexed: false },
      {
        name: 'streamsHistoryHashes',
        internalType: 'bytes32[]',
        type: 'bytes32[]',
        indexed: false,
      },
    ],
    name: 'SqueezedStreams',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'receiversHash', internalType: 'bytes32', type: 'bytes32', indexed: true },
      { name: 'accountId', internalType: 'uint256', type: 'uint256', indexed: true },
      { name: 'config', internalType: 'StreamConfig', type: 'uint256', indexed: false },
    ],
    name: 'StreamReceiverSeen',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'accountId', internalType: 'uint256', type: 'uint256', indexed: true },
      { name: 'erc20', internalType: 'contract IERC20', type: 'address', indexed: true },
      { name: 'receiversHash', internalType: 'bytes32', type: 'bytes32', indexed: true },
      {
        name: 'streamsHistoryHash',
        internalType: 'bytes32',
        type: 'bytes32',
        indexed: false,
      },
      { name: 'balance', internalType: 'uint128', type: 'uint128', indexed: false },
      { name: 'maxEnd', internalType: 'uint32', type: 'uint32', indexed: false },
    ],
    name: 'StreamsSet',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'pauser', internalType: 'address', type: 'address', indexed: true }],
    name: 'Unpaused',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'implementation', internalType: 'address', type: 'address', indexed: true },
    ],
    name: 'Upgraded',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'erc20', internalType: 'contract IERC20', type: 'address', indexed: true },
      { name: 'receiver', internalType: 'address', type: 'address', indexed: true },
      { name: 'amt', internalType: 'uint256', type: 'uint256', indexed: false },
    ],
    name: 'Withdrawn',
  },
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// DripsFacetB
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const dripsFacetBAbi = [
  { type: 'constructor', inputs: [], stateMutability: 'nonpayable' },
  {
    type: 'function',
    inputs: [],
    name: 'DRIVER_ID_OFFSET',
    outputs: [{ name: '', internalType: 'uint8', type: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'MAX_SPLITS_RECEIVERS',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'MAX_TOTAL_BALANCE',
    outputs: [{ name: '', internalType: 'uint128', type: 'uint128' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'TOTAL_SPLITS_WEIGHT',
    outputs: [{ name: '', internalType: 'uint32', type: 'uint32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'acceptAdmin',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'admin',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'allPausers',
    outputs: [{ name: 'pausersList', internalType: 'address[]', type: 'address[]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'accountId', internalType: 'uint256', type: 'uint256' },
      { name: 'erc20', internalType: 'contract IERC20', type: 'address' },
    ],
    name: 'collect',
    outputs: [{ name: 'amt', internalType: 'uint128', type: 'uint128' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'accountId', internalType: 'uint256', type: 'uint256' },
      { name: 'erc20', internalType: 'contract IERC20', type: 'address' },
    ],
    name: 'collectable',
    outputs: [{ name: 'amt', internalType: 'uint128', type: 'uint128' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'accountId', internalType: 'uint256', type: 'uint256' },
      {
        name: 'accountMetadata',
        internalType: 'struct AccountMetadata[]',
        type: 'tuple[]',
        components: [
          { name: 'key', internalType: 'bytes32', type: 'bytes32' },
          { name: 'value', internalType: 'bytes', type: 'bytes' },
        ],
      },
    ],
    name: 'emitAccountMetadata',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'accountId', internalType: 'uint256', type: 'uint256' },
      { name: 'erc20', internalType: 'contract IERC20', type: 'address' },
      { name: 'yieldManager', internalType: 'address', type: 'address' },
      { name: 'strategy', internalType: 'address', type: 'address' },
      { name: 'senderAccountId', internalType: 'uint256', type: 'uint256' },
      { name: 'transferTo', internalType: 'address', type: 'address' },
    ],
    name: 'forceCollect',
    outputs: [{ name: 'amt', internalType: 'uint128', type: 'uint128' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'accountId', internalType: 'uint256', type: 'uint256' },
      { name: 'receiver', internalType: 'uint256', type: 'uint256' },
      { name: 'erc20', internalType: 'contract IERC20', type: 'address' },
      { name: 'amt', internalType: 'uint128', type: 'uint128' },
    ],
    name: 'give',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'pauser', internalType: 'address', type: 'address' }],
    name: 'grantPauser',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'implementation',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'isPaused',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'pauser', internalType: 'address', type: 'address' }],
    name: 'isPauser',
    outputs: [{ name: 'isAddrPauser', internalType: 'bool', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'pause',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'newAdmin', internalType: 'address', type: 'address' }],
    name: 'proposeNewAdmin',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'proposedAdmin',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'proxiableUUID',
    outputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'renounceAdmin',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'pauser', internalType: 'address', type: 'address' }],
    name: 'revokePauser',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'accountId', internalType: 'uint256', type: 'uint256' },
      {
        name: 'receivers',
        internalType: 'struct SplitsReceiver[]',
        type: 'tuple[]',
        components: [
          { name: 'accountId', internalType: 'uint256', type: 'uint256' },
          { name: 'weight', internalType: 'uint32', type: 'uint32' },
        ],
      },
    ],
    name: 'setSplits',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'accountId', internalType: 'uint256', type: 'uint256' },
      { name: 'erc20', internalType: 'contract IERC20', type: 'address' },
      {
        name: 'currReceivers',
        internalType: 'struct SplitsReceiver[]',
        type: 'tuple[]',
        components: [
          { name: 'accountId', internalType: 'uint256', type: 'uint256' },
          { name: 'weight', internalType: 'uint32', type: 'uint32' },
        ],
      },
    ],
    name: 'split',
    outputs: [
      { name: 'collectableAmt', internalType: 'uint128', type: 'uint128' },
      { name: 'splitAmt', internalType: 'uint128', type: 'uint128' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'accountId', internalType: 'uint256', type: 'uint256' },
      { name: 'erc20', internalType: 'contract IERC20', type: 'address' },
    ],
    name: 'splittable',
    outputs: [{ name: 'amt', internalType: 'uint128', type: 'uint128' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'unpause',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'newImplementation', internalType: 'address', type: 'address' }],
    name: 'upgradeTo',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'newImplementation', internalType: 'address', type: 'address' },
      { name: 'data', internalType: 'bytes', type: 'bytes' },
    ],
    name: 'upgradeToAndCall',
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'accountId', internalType: 'uint256', type: 'uint256', indexed: true },
      { name: 'key', internalType: 'bytes32', type: 'bytes32', indexed: true },
      { name: 'value', internalType: 'bytes', type: 'bytes', indexed: false },
    ],
    name: 'AccountMetadataEmitted',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'previousAdmin', internalType: 'address', type: 'address', indexed: false },
      { name: 'newAdmin', internalType: 'address', type: 'address', indexed: false },
    ],
    name: 'AdminChanged',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'beacon', internalType: 'address', type: 'address', indexed: true }],
    name: 'BeaconUpgraded',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'accountId', internalType: 'uint256', type: 'uint256', indexed: true },
      { name: 'erc20', internalType: 'contract IERC20', type: 'address', indexed: true },
      { name: 'amt', internalType: 'uint128', type: 'uint128', indexed: false },
    ],
    name: 'Collectable',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'accountId', internalType: 'uint256', type: 'uint256', indexed: true },
      { name: 'erc20', internalType: 'contract IERC20', type: 'address', indexed: true },
      { name: 'collected', internalType: 'uint128', type: 'uint128', indexed: false },
    ],
    name: 'Collected',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'accountId', internalType: 'uint256', type: 'uint256', indexed: true },
      { name: 'receiver', internalType: 'uint256', type: 'uint256', indexed: true },
      { name: 'erc20', internalType: 'contract IERC20', type: 'address', indexed: true },
      { name: 'amt', internalType: 'uint128', type: 'uint128', indexed: false },
    ],
    name: 'Given',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'currentAdmin', internalType: 'address', type: 'address', indexed: true },
      { name: 'newAdmin', internalType: 'address', type: 'address', indexed: true },
    ],
    name: 'NewAdminProposed',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'pauser', internalType: 'address', type: 'address', indexed: true }],
    name: 'Paused',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'pauser', internalType: 'address', type: 'address', indexed: true },
      { name: 'admin', internalType: 'address', type: 'address', indexed: true },
    ],
    name: 'PauserGranted',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'pauser', internalType: 'address', type: 'address', indexed: true },
      { name: 'admin', internalType: 'address', type: 'address', indexed: true },
    ],
    name: 'PauserRevoked',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'accountId', internalType: 'uint256', type: 'uint256', indexed: true },
      { name: 'receiver', internalType: 'uint256', type: 'uint256', indexed: true },
      { name: 'erc20', internalType: 'contract IERC20', type: 'address', indexed: true },
      { name: 'amt', internalType: 'uint128', type: 'uint128', indexed: false },
    ],
    name: 'Split',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'receiversHash', internalType: 'bytes32', type: 'bytes32', indexed: true },
      { name: 'accountId', internalType: 'uint256', type: 'uint256', indexed: true },
      { name: 'weight', internalType: 'uint32', type: 'uint32', indexed: false },
    ],
    name: 'SplitsReceiverSeen',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'accountId', internalType: 'uint256', type: 'uint256', indexed: true },
      { name: 'receiversHash', internalType: 'bytes32', type: 'bytes32', indexed: true },
    ],
    name: 'SplitsSet',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'pauser', internalType: 'address', type: 'address', indexed: true }],
    name: 'Unpaused',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'implementation', internalType: 'address', type: 'address', indexed: true },
    ],
    name: 'Upgraded',
  },
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// DripsRouter
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const dripsRouterAbi = [
  {
    type: 'constructor',
    inputs: [
      { name: 'facetA_', internalType: 'address', type: 'address' },
      { name: 'facetB_', internalType: 'address', type: 'address' },
      { name: 'driverId_', internalType: 'uint32', type: 'uint32' },
      { name: 'privacyAdmin_', internalType: 'address', type: 'address' },
    ],
    stateMutability: 'nonpayable',
  },
  { type: 'fallback', stateMutability: 'payable' },
  { type: 'receive', stateMutability: 'payable' },
  {
    type: 'function',
    inputs: [],
    name: 'DRIVER_ID',
    outputs: [{ name: '', internalType: 'uint32', type: 'uint32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'FACET_A',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'FACET_B',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'addr', internalType: 'address', type: 'address' }],
    name: 'calcAccountId',
    outputs: [{ name: 'accountId', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'erc20', internalType: 'contract IERC20', type: 'address' },
      { name: 'transferTo', internalType: 'address', type: 'address' },
      { name: 'doRemint', internalType: 'bool', type: 'bool' },
      {
        name: 'remintData',
        internalType: 'struct IERC8065.RemintData',
        type: 'tuple',
        components: [
          { name: 'commitment', internalType: 'bytes32', type: 'bytes32' },
          { name: 'nullifiers', internalType: 'bytes32[]', type: 'bytes32[]' },
          { name: 'proverData', internalType: 'bytes', type: 'bytes' },
          { name: 'relayerData', internalType: 'bytes', type: 'bytes' },
          { name: 'redeem', internalType: 'bool', type: 'bool' },
          { name: 'proof', internalType: 'bytes', type: 'bytes' },
        ],
      },
      { name: 'redeemRaw', internalType: 'bool', type: 'bool' },
    ],
    name: 'collectPrivate',
    outputs: [{ name: 'amt', internalType: 'uint128', type: 'uint128' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'erc20', internalType: 'contract IERC20', type: 'address' },
      { name: 'amount', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'deposit',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'receiver', internalType: 'uint256', type: 'uint256' },
      { name: 'erc20', internalType: 'contract IERC20', type: 'address' },
      { name: 'amt', internalType: 'uint128', type: 'uint128' },
    ],
    name: 'givePrivate',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'privacyAdmin',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'underlying', internalType: 'contract IERC20', type: 'address' },
      { name: 'zwToken', internalType: 'contract IERC8065', type: 'address' },
    ],
    name: 'registerZwToken',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'erc20', internalType: 'contract IERC20', type: 'address' },
      {
        name: 'currReceivers',
        internalType: 'struct StreamReceiver[]',
        type: 'tuple[]',
        components: [
          { name: 'accountId', internalType: 'uint256', type: 'uint256' },
          { name: 'config', internalType: 'StreamConfig', type: 'uint256' },
        ],
      },
      { name: 'balanceDelta', internalType: 'int128', type: 'int128' },
      {
        name: 'newReceivers',
        internalType: 'struct StreamReceiver[]',
        type: 'tuple[]',
        components: [
          { name: 'accountId', internalType: 'uint256', type: 'uint256' },
          { name: 'config', internalType: 'StreamConfig', type: 'uint256' },
        ],
      },
      { name: 'maxEndHint1', internalType: 'uint32', type: 'uint32' },
      { name: 'maxEndHint2', internalType: 'uint32', type: 'uint32' },
      { name: 'transferTo', internalType: 'address', type: 'address' },
    ],
    name: 'setStreamsPrivate',
    outputs: [{ name: 'realBalanceDelta', internalType: 'int128', type: 'int128' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'erc20', internalType: 'contract IERC20', type: 'address' },
      { name: 'amount', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'withdraw',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: '', internalType: 'contract IERC20', type: 'address' }],
    name: 'zwTokens',
    outputs: [{ name: '', internalType: 'contract IERC8065', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'accountId', internalType: 'uint256', type: 'uint256', indexed: true },
      {
        name: 'zwToken',
        internalType: 'contract IERC8065',
        type: 'address',
        indexed: true,
      },
      { name: 'amt', internalType: 'uint128', type: 'uint128', indexed: false },
    ],
    name: 'PrivateCollected',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'accountId', internalType: 'uint256', type: 'uint256', indexed: true },
      { name: 'receiver', internalType: 'uint256', type: 'uint256', indexed: true },
      {
        name: 'zwToken',
        internalType: 'contract IERC8065',
        type: 'address',
        indexed: true,
      },
      { name: 'amt', internalType: 'uint128', type: 'uint128', indexed: false },
    ],
    name: 'PrivateGiven',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'accountId', internalType: 'uint256', type: 'uint256', indexed: true },
      {
        name: 'zwToken',
        internalType: 'contract IERC8065',
        type: 'address',
        indexed: true,
      },
      { name: 'realBalanceDelta', internalType: 'int128', type: 'int128', indexed: false },
    ],
    name: 'PrivateStreamSet',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'underlying',
        internalType: 'contract IERC20',
        type: 'address',
        indexed: true,
      },
      {
        name: 'zwToken',
        internalType: 'contract IERC8065',
        type: 'address',
        indexed: true,
      },
    ],
    name: 'ZwTokenRegistered',
  },
  { type: 'error', inputs: [], name: 'BalanceOverflow' },
  { type: 'error', inputs: [], name: 'DelegatecallFailed' },
  { type: 'error', inputs: [], name: 'NotAdmin' },
  { type: 'error', inputs: [], name: 'ZeroAddress' },
  { type: 'error', inputs: [], name: 'ZeroAmount' },
  {
    type: 'error',
    inputs: [{ name: 'erc20', internalType: 'contract IERC20', type: 'address' }],
    name: 'ZwTokenNotRegistered',
  },
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// ERC20
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const erc20Abi = [
  {
    type: 'constructor',
    inputs: [
      { name: 'name_', internalType: 'string', type: 'string' },
      { name: 'symbol_', internalType: 'string', type: 'string' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'owner', internalType: 'address', type: 'address' },
      { name: 'spender', internalType: 'address', type: 'address' },
    ],
    name: 'allowance',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'spender', internalType: 'address', type: 'address' },
      { name: 'amount', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'approve',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'account', internalType: 'address', type: 'address' }],
    name: 'balanceOf',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'decimals',
    outputs: [{ name: '', internalType: 'uint8', type: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'spender', internalType: 'address', type: 'address' },
      { name: 'subtractedValue', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'decreaseAllowance',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'spender', internalType: 'address', type: 'address' },
      { name: 'addedValue', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'increaseAllowance',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'name',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'symbol',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'totalSupply',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'to', internalType: 'address', type: 'address' },
      { name: 'amount', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'transfer',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'from', internalType: 'address', type: 'address' },
      { name: 'to', internalType: 'address', type: 'address' },
      { name: 'amount', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'transferFrom',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'owner', internalType: 'address', type: 'address', indexed: true },
      { name: 'spender', internalType: 'address', type: 'address', indexed: true },
      { name: 'value', internalType: 'uint256', type: 'uint256', indexed: false },
    ],
    name: 'Approval',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'from', internalType: 'address', type: 'address', indexed: true },
      { name: 'to', internalType: 'address', type: 'address', indexed: true },
      { name: 'value', internalType: 'uint256', type: 'uint256', indexed: false },
    ],
    name: 'Transfer',
  },
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// IDrips
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const iDripsAbi = [
  {
    type: 'function',
    inputs: [],
    name: 'AMT_PER_SEC_MULTIPLIER',
    outputs: [{ name: '', internalType: 'uint160', type: 'uint160' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'erc20', internalType: 'contract IERC20', type: 'address' }],
    name: 'balances',
    outputs: [
      { name: 'streamsBalance', internalType: 'uint128', type: 'uint128' },
      { name: 'splitsBalance', internalType: 'uint128', type: 'uint128' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'accountId', internalType: 'uint256', type: 'uint256' },
      { name: 'erc20', internalType: 'contract IERC20', type: 'address' },
    ],
    name: 'collect',
    outputs: [{ name: 'amt', internalType: 'uint128', type: 'uint128' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'accountId', internalType: 'uint256', type: 'uint256' },
      { name: 'erc20', internalType: 'contract IERC20', type: 'address' },
    ],
    name: 'collectable',
    outputs: [{ name: 'amt', internalType: 'uint128', type: 'uint128' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'cycleSecs',
    outputs: [{ name: '', internalType: 'uint32', type: 'uint32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'driverId', internalType: 'uint32', type: 'uint32' }],
    name: 'driverAddress',
    outputs: [{ name: 'driverAddr', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'accountId', internalType: 'uint256', type: 'uint256' },
      {
        name: 'accountMetadata',
        internalType: 'struct AccountMetadata[]',
        type: 'tuple[]',
        components: [
          { name: 'key', internalType: 'bytes32', type: 'bytes32' },
          { name: 'value', internalType: 'bytes', type: 'bytes' },
        ],
      },
    ],
    name: 'emitAccountMetadata',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'accountId', internalType: 'uint256', type: 'uint256' },
      { name: 'erc20', internalType: 'contract IERC20', type: 'address' },
      { name: 'yieldManager', internalType: 'address', type: 'address' },
      { name: 'strategy', internalType: 'address', type: 'address' },
      { name: 'senderAccountId', internalType: 'uint256', type: 'uint256' },
      { name: 'transferTo', internalType: 'address', type: 'address' },
    ],
    name: 'forceCollect',
    outputs: [{ name: 'amt', internalType: 'uint128', type: 'uint128' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'accountId', internalType: 'uint256', type: 'uint256' },
      { name: 'receiver', internalType: 'uint256', type: 'uint256' },
      { name: 'erc20', internalType: 'contract IERC20', type: 'address' },
      { name: 'amt', internalType: 'uint128', type: 'uint128' },
    ],
    name: 'give',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'minAmtPerSec',
    outputs: [{ name: '', internalType: 'uint160', type: 'uint160' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'nextDriverId',
    outputs: [{ name: 'driverId', internalType: 'uint32', type: 'uint32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'accountId', internalType: 'uint256', type: 'uint256' },
      { name: 'erc20', internalType: 'contract IERC20', type: 'address' },
      { name: 'maxCycles', internalType: 'uint32', type: 'uint32' },
    ],
    name: 'receiveStreams',
    outputs: [{ name: 'receivedAmt', internalType: 'uint128', type: 'uint128' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'driverAddr', internalType: 'address', type: 'address' }],
    name: 'registerDriver',
    outputs: [{ name: 'driverId', internalType: 'uint32', type: 'uint32' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'accountId', internalType: 'uint256', type: 'uint256' },
      {
        name: 'receivers',
        internalType: 'struct SplitsReceiver[]',
        type: 'tuple[]',
        components: [
          { name: 'accountId', internalType: 'uint256', type: 'uint256' },
          { name: 'weight', internalType: 'uint32', type: 'uint32' },
        ],
      },
    ],
    name: 'setSplits',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'accountId', internalType: 'uint256', type: 'uint256' },
      { name: 'erc20', internalType: 'contract IERC20', type: 'address' },
      {
        name: 'currReceivers',
        internalType: 'struct StreamReceiver[]',
        type: 'tuple[]',
        components: [
          { name: 'accountId', internalType: 'uint256', type: 'uint256' },
          { name: 'config', internalType: 'StreamConfig', type: 'uint256' },
        ],
      },
      { name: 'balanceDelta', internalType: 'int128', type: 'int128' },
      {
        name: 'newReceivers',
        internalType: 'struct StreamReceiver[]',
        type: 'tuple[]',
        components: [
          { name: 'accountId', internalType: 'uint256', type: 'uint256' },
          { name: 'config', internalType: 'StreamConfig', type: 'uint256' },
        ],
      },
      { name: 'maxEndHint1', internalType: 'uint32', type: 'uint32' },
      { name: 'maxEndHint2', internalType: 'uint32', type: 'uint32' },
    ],
    name: 'setStreams',
    outputs: [{ name: 'realBalanceDelta', internalType: 'int128', type: 'int128' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'accountId', internalType: 'uint256', type: 'uint256' },
      { name: 'erc20', internalType: 'contract IERC20', type: 'address' },
      {
        name: 'currReceivers',
        internalType: 'struct SplitsReceiver[]',
        type: 'tuple[]',
        components: [
          { name: 'accountId', internalType: 'uint256', type: 'uint256' },
          { name: 'weight', internalType: 'uint32', type: 'uint32' },
        ],
      },
    ],
    name: 'split',
    outputs: [
      { name: 'collectableAmt', internalType: 'uint128', type: 'uint128' },
      { name: 'splitAmt', internalType: 'uint128', type: 'uint128' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'accountId', internalType: 'uint256', type: 'uint256' },
      { name: 'erc20', internalType: 'contract IERC20', type: 'address' },
    ],
    name: 'splittable',
    outputs: [{ name: 'amt', internalType: 'uint128', type: 'uint128' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'accountId', internalType: 'uint256', type: 'uint256' },
      { name: 'erc20', internalType: 'contract IERC20', type: 'address' },
    ],
    name: 'streamsState',
    outputs: [
      { name: '', internalType: 'bytes32', type: 'bytes32' },
      { name: '', internalType: 'bytes32', type: 'bytes32' },
      { name: '', internalType: 'uint32', type: 'uint32' },
      { name: '', internalType: 'uint128', type: 'uint128' },
      { name: '', internalType: 'uint32', type: 'uint32' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'driverId', internalType: 'uint32', type: 'uint32' },
      { name: 'newDriverAddr', internalType: 'address', type: 'address' },
    ],
    name: 'updateDriverAddress',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'erc20', internalType: 'contract IERC20', type: 'address' },
      { name: 'receiver', internalType: 'address', type: 'address' },
      { name: 'amt', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'withdraw',
    outputs: [],
    stateMutability: 'nonpayable',
  },
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// ZWERC20
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const zwerc20Abi = [
  {
    type: 'constructor',
    inputs: [
      { name: 'name_', internalType: 'string', type: 'string' },
      { name: 'symbol_', internalType: 'string', type: 'string' },
      { name: 'decimals_', internalType: 'uint8', type: 'uint8' },
      { name: 'underlying_', internalType: 'address', type: 'address' },
      {
        name: 'config',
        internalType: 'struct BaseZWToken.ZwConfig',
        type: 'tuple',
        components: [
          { name: 'verifier', internalType: 'address', type: 'address' },
          { name: 'feeCollector', internalType: 'address', type: 'address' },
          { name: 'feeDenominator', internalType: 'uint256', type: 'uint256' },
          { name: 'depositFee', internalType: 'uint256', type: 'uint256' },
          { name: 'remintFee', internalType: 'uint256', type: 'uint256' },
          { name: 'withdrawFee', internalType: 'uint256', type: 'uint256' },
          { name: 'minDepositFee', internalType: 'uint256', type: 'uint256' },
          { name: 'minWithdrawFee', internalType: 'uint256', type: 'uint256' },
          { name: 'minRemintFee', internalType: 'uint256', type: 'uint256' },
        ],
      },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'DEPOSIT_FEE',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'FEE_COLLECTOR',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'FEE_DENOMINATOR',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'MAX_LEAVES',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'REMINT_FEE',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'TREE_DEPTH',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'UNDERLYING',
    outputs: [{ name: '', internalType: 'contract IERC20', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'VERIFIER',
    outputs: [{ name: '', internalType: 'contract ISnarkVerifier', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'WITHDRAW_FEE',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'owner', internalType: 'address', type: 'address' },
      { name: 'spender', internalType: 'address', type: 'address' },
    ],
    name: 'allowance',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'spender', internalType: 'address', type: 'address' },
      { name: 'amount', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'approve',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'account', internalType: 'address', type: 'address' }],
    name: 'balanceOf',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
    name: 'commitmentToIndex',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'decimals',
    outputs: [{ name: '', internalType: 'uint8', type: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'spender', internalType: 'address', type: 'address' },
      { name: 'subtractedValue', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'decreaseAllowance',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'to', internalType: 'address', type: 'address' },
      { name: 'id', internalType: 'uint256', type: 'uint256' },
      { name: 'amount', internalType: 'uint256', type: 'uint256' },
      { name: 'data', internalType: 'bytes', type: 'bytes' },
    ],
    name: 'deposit',
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    inputs: [{ name: 'id', internalType: 'uint256', type: 'uint256' }],
    name: 'getCommitLeafCount',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'id', internalType: 'uint256', type: 'uint256' },
      { name: 'startIndex', internalType: 'uint256', type: 'uint256' },
      { name: 'length', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'getCommitLeaves',
    outputs: [
      { name: 'commitHashes', internalType: 'bytes32[]', type: 'bytes32[]' },
      { name: 'recipients', internalType: 'address[]', type: 'address[]' },
      { name: 'amounts', internalType: 'uint256[]', type: 'uint256[]' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'getFeeConfig',
    outputs: [
      { name: 'depositFee_', internalType: 'uint256', type: 'uint256' },
      { name: 'remintFee_', internalType: 'uint256', type: 'uint256' },
      { name: 'withdrawFee_', internalType: 'uint256', type: 'uint256' },
      { name: 'feeDenominator_', internalType: 'uint256', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'level', internalType: 'uint256', type: 'uint256' }],
    name: 'getFilledSubtree',
    outputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'id', internalType: 'uint256', type: 'uint256' }],
    name: 'getLatestCommitment',
    outputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'getLeafCount',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'getMinFeeConfig',
    outputs: [
      { name: 'minDepositFee_', internalType: 'uint256', type: 'uint256' },
      { name: 'minWithdrawFee_', internalType: 'uint256', type: 'uint256' },
      { name: 'minRemintFee_', internalType: 'uint256', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'getUnderlying',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'level', internalType: 'uint256', type: 'uint256' }],
    name: 'getZeroHash',
    outputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'id', internalType: 'uint256', type: 'uint256' },
      { name: 'commitment', internalType: 'bytes32', type: 'bytes32' },
    ],
    name: 'hasCommitment',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: '', internalType: 'address', type: 'address' }],
    name: 'hasFirstReceiptRecorded',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'spender', internalType: 'address', type: 'address' },
      { name: 'addedValue', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'increaseAllowance',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'isFull',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
    name: 'isKnownRoot',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'minDepositFee',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'minRemintFee',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'minWithdrawFee',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'name',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'nextIndex',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
    name: 'nullifierUsed',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'to', internalType: 'address', type: 'address' },
      { name: 'id', internalType: 'uint256', type: 'uint256' },
      { name: 'amount', internalType: 'uint256', type: 'uint256' },
      { name: 'data', internalType: 'bytes', type: 'bytes' },
    ],
    name: 'previewDeposit',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'to', internalType: 'address', type: 'address' },
      { name: 'id', internalType: 'uint256', type: 'uint256' },
      { name: 'amount', internalType: 'uint256', type: 'uint256' },
      {
        name: 'data',
        internalType: 'struct IERC8065.RemintData',
        type: 'tuple',
        components: [
          { name: 'commitment', internalType: 'bytes32', type: 'bytes32' },
          { name: 'nullifiers', internalType: 'bytes32[]', type: 'bytes32[]' },
          { name: 'proverData', internalType: 'bytes', type: 'bytes' },
          { name: 'relayerData', internalType: 'bytes', type: 'bytes' },
          { name: 'redeem', internalType: 'bool', type: 'bool' },
          { name: 'proof', internalType: 'bytes', type: 'bytes' },
        ],
      },
    ],
    name: 'previewRemint',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'to', internalType: 'address', type: 'address' },
      { name: 'id', internalType: 'uint256', type: 'uint256' },
      { name: 'amount', internalType: 'uint256', type: 'uint256' },
      { name: 'data', internalType: 'bytes', type: 'bytes' },
    ],
    name: 'previewWithdraw',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'to', internalType: 'address', type: 'address' },
      { name: 'id', internalType: 'uint256', type: 'uint256' },
      { name: 'amount', internalType: 'uint256', type: 'uint256' },
      {
        name: 'data',
        internalType: 'struct IERC8065.RemintData',
        type: 'tuple',
        components: [
          { name: 'commitment', internalType: 'bytes32', type: 'bytes32' },
          { name: 'nullifiers', internalType: 'bytes32[]', type: 'bytes32[]' },
          { name: 'proverData', internalType: 'bytes', type: 'bytes' },
          { name: 'relayerData', internalType: 'bytes', type: 'bytes' },
          { name: 'redeem', internalType: 'bool', type: 'bool' },
          { name: 'proof', internalType: 'bytes', type: 'bytes' },
        ],
      },
    ],
    name: 'remint',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'root',
    outputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: '_minDepositFee', internalType: 'uint256', type: 'uint256' },
      { name: '_minWithdrawFee', internalType: 'uint256', type: 'uint256' },
      { name: '_minRemintFee', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'setMinFees',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'symbol',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'totalSupply',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'to', internalType: 'address', type: 'address' },
      { name: 'amount', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'transfer',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'from', internalType: 'address', type: 'address' },
      { name: 'to', internalType: 'address', type: 'address' },
      { name: 'amount', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'transferFrom',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'to', internalType: 'address', type: 'address' },
      { name: 'id', internalType: 'uint256', type: 'uint256' },
      { name: 'amount', internalType: 'uint256', type: 'uint256' },
      { name: 'data', internalType: 'bytes', type: 'bytes' },
    ],
    name: 'withdraw',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'owner', internalType: 'address', type: 'address', indexed: true },
      { name: 'spender', internalType: 'address', type: 'address', indexed: true },
      { name: 'value', internalType: 'uint256', type: 'uint256', indexed: false },
    ],
    name: 'Approval',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'id', internalType: 'uint256', type: 'uint256', indexed: true },
      { name: 'commitment', internalType: 'bytes32', type: 'bytes32', indexed: true },
      { name: 'to', internalType: 'address', type: 'address', indexed: true },
      { name: 'amount', internalType: 'uint256', type: 'uint256', indexed: false },
    ],
    name: 'CommitmentUpdated',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'from', internalType: 'address', type: 'address', indexed: true },
      { name: 'to', internalType: 'address', type: 'address', indexed: true },
      { name: 'id', internalType: 'uint256', type: 'uint256', indexed: true },
      { name: 'amount', internalType: 'uint256', type: 'uint256', indexed: false },
    ],
    name: 'Deposited',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'index', internalType: 'uint256', type: 'uint256', indexed: true },
      { name: 'leaf', internalType: 'bytes32', type: 'bytes32', indexed: true },
    ],
    name: 'LeafInserted',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'from', internalType: 'address', type: 'address', indexed: true },
      { name: 'to', internalType: 'address', type: 'address', indexed: true },
      { name: 'id', internalType: 'uint256', type: 'uint256', indexed: true },
      { name: 'amount', internalType: 'uint256', type: 'uint256', indexed: false },
      { name: 'redeem', internalType: 'bool', type: 'bool', indexed: false },
    ],
    name: 'Reminted',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'oldRoot', internalType: 'bytes32', type: 'bytes32', indexed: true },
      { name: 'newRoot', internalType: 'bytes32', type: 'bytes32', indexed: true },
    ],
    name: 'RootUpdated',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'from', internalType: 'address', type: 'address', indexed: true },
      { name: 'to', internalType: 'address', type: 'address', indexed: true },
      { name: 'value', internalType: 'uint256', type: 'uint256', indexed: false },
    ],
    name: 'Transfer',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'from', internalType: 'address', type: 'address', indexed: true },
      { name: 'to', internalType: 'address', type: 'address', indexed: true },
      { name: 'id', internalType: 'uint256', type: 'uint256', indexed: true },
      { name: 'amount', internalType: 'uint256', type: 'uint256', indexed: false },
    ],
    name: 'Withdrawn',
  },
  { type: 'error', inputs: [], name: 'InvalidAmount' },
  { type: 'error', inputs: [], name: 'InvalidDepth' },
  { type: 'error', inputs: [], name: 'InvalidFee' },
  { type: 'error', inputs: [], name: 'InvalidProof' },
  { type: 'error', inputs: [], name: 'InvalidRoot' },
  { type: 'error', inputs: [], name: 'InvalidTokenId' },
  { type: 'error', inputs: [], name: 'NullifierUsed' },
  { type: 'error', inputs: [], name: 'TransferFailed' },
  { type: 'error', inputs: [], name: 'TreeFull' },
] as const
